# Generated by Django 4.1.13 on 2024-10-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='categoria',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
