# Generated by Django 4.1.13 on 2024-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0002_fondo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondo',
            name='categoria',
            field=models.CharField(choices=[('FPV', 'Fondo Voluntario de Pension'), ('FIC', 'Fondos de Inversion Colectiva')], max_length=3),
        ),
    ]
