# Generated by Django 4.1.13 on 2024-10-07 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0004_alter_transaccion_identificador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha',
        ),
    ]
