# Generated by Django 4.1.13 on 2024-10-07 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0005_remove_transaccion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
